language: node_js
node_js:
  - "lts/*"

sudo: required

branchs:
  only:
  - master

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn install

script:
  - yarn prepare:env
  - yarn tslint
  - yarn test

notifications:
  email:
    - binshao54@gmail.com
  on_success: always
  on_failure: always
  